//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PayId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string CardNo { get; set; }
        public string BankName { get; set; }
        public string NameOnCard { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
